[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Make sure environment variables are available to functions
[context.production.environment]
  VITE_STEAMGRIDDB_API_KEY = "${VITE_STEAMGRIDDB_API_KEY}"

[context.deploy-preview.environment]  
  VITE_STEAMGRIDDB_API_KEY = "${VITE_STEAMGRIDDB_API_KEY}"

[context.branch-deploy.environment]
  VITE_STEAMGRIDDB_API_KEY = "${VITE_STEAMGRIDDB_API_KEY}"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
